import asyncio
import json
import logging
from abc import ABC, abstractmethod
from typing import Any, AsyncGenerator, Dict, List, Optional
import httpx
import anthropic

try:
    import claude_agent_sdk
    from claude_agent_sdk import ClaudeSDKClient, ClaudeAgentOptions
    from claude_agent_sdk.types import StreamEvent, AssistantMessage, TextBlock
    HAS_CLAUDE_AGENT_SDK = True
except ImportError:
    claude_agent_sdk = None
    HAS_CLAUDE_AGENT_SDK = False

from app.config import settings
from app.exceptions import (
    ClaudeNotConfiguredError,
    OllamaUnavailableError,
    ModelUnavailableError,
    ModelTimeoutError,
)

logger = logging.getLogger("agent.provider")


class LLMProvider(ABC):
    """Abstract interface for reasoning model providers (Anthropic Claude or local Ollama)."""

    @property
    @abstractmethod
    def provider_name(self) -> str:
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        pass

    @abstractmethod
    async def stream_chat(
        self,
        system_prompt: str,
        messages: List[Dict[str, str]],
        timeout: Optional[float] = None,
        num_predict: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        """Stream incremental text tokens from the reasoning model.

        Yields:
            str: text deltas generated by the model.

        Raises:
            ClaudeNotConfiguredError
            OllamaUnavailableError
            ModelUnavailableError
            ModelTimeoutError
        """
        pass


class AnthropicProvider(LLMProvider):
    """Reasoning provider using Claude Agent SDK / Anthropic Python SDK."""

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self._api_key = api_key or settings.anthropic_api_key
        self._model = model or settings.anthropic_model

    @property
    def provider_name(self) -> str:
        return "anthropic"

    @property
    def model_name(self) -> str:
        return self._model

    @property
    def uses_claude_agent_sdk(self) -> bool:
        return HAS_CLAUDE_AGENT_SDK

    async def stream_chat(
        self,
        system_prompt: str,
        messages: List[Dict[str, str]],
        timeout: Optional[float] = None,
        num_predict: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        eff_timeout = timeout or settings.model_timeout_seconds
        # num_predict is ignored for Anthropic (uses different token limits)

        if not self._api_key or not self._api_key.strip():
            logger.warning(
                "provider_unavailable",
                extra={"provider": "anthropic", "reason": "missing_api_key"},
            )
            raise ClaudeNotConfiguredError(
                "Anthropic Claude API key is not configured. Please set ANTHROPIC_API_KEY."
            )

        client = anthropic.AsyncAnthropic(api_key=self._api_key)

        # Format messages for Anthropic (roles: 'user' and 'assistant')
        anthropic_messages = []
        for msg in messages:
            role = msg["role"]
            if role not in ("user", "assistant"):
                role = "user"
            anthropic_messages.append({"role": role, "content": msg["content"]})

        try:
            async def _stream_runner():
                async with client.messages.stream(
                    model=self._model,
                    system=system_prompt,
                    messages=anthropic_messages,
                    max_tokens=4096,
                ) as stream:
                    async for delta in stream.text_stream:
                        yield delta

            # Stream with timeout
            runner = _stream_runner()
            deadline = asyncio.get_event_loop().time() + eff_timeout
            while True:
                remaining = deadline - asyncio.get_event_loop().time()
                if remaining <= 0:
                    raise asyncio.TimeoutError()
                try:
                    delta = await asyncio.wait_for(runner.__anext__(), timeout=remaining)
                    yield delta
                except StopAsyncIteration:
                    break

        except (asyncio.TimeoutError, TimeoutError) as e:
            logger.error(
                "provider_timeout",
                extra={"provider": "anthropic", "model": self._model, "timeout": eff_timeout},
            )
            raise ModelTimeoutError(
                f"Anthropic inference timed out after {eff_timeout} seconds."
            ) from e
        except anthropic.APIConnectionError as e:
            logger.error("provider_unavailable", extra={"provider": "anthropic", "error": str(e)})
            raise ModelUnavailableError("Unable to connect to Anthropic API.") from e
        except anthropic.RateLimitError as e:
            logger.error("provider_rate_limit", extra={"provider": "anthropic", "error": str(e)})
            raise ModelUnavailableError("Anthropic rate limit reached. Please retry later.") from e
        except anthropic.APIStatusError as e:
            logger.error("provider_status_error", extra={"provider": "anthropic", "status": e.status_code})
            raise ModelUnavailableError(f"Anthropic API returned error: {e.message}") from e
        except Exception as e:
            if isinstance(e, (ClaudeNotConfiguredError, ModelTimeoutError, ModelUnavailableError)):
                raise
            logger.error("agent_generation_failed", extra={"provider": "anthropic", "error": str(e)})
            raise ModelUnavailableError(f"Anthropic generation error: {str(e)}") from e



class OllamaProvider(LLMProvider):
    """Reasoning provider using local Ollama instance."""

    def __init__(self, base_url: Optional[str] = None, model: Optional[str] = None):
        self._base_url = (base_url or settings.ollama_base_url).rstrip("/")
        self._model = model or settings.ollama_model

    @property
    def provider_name(self) -> str:
        return "ollama"

    @property
    def model_name(self) -> str:
        return self._model

    async def stream_chat(
        self,
        system_prompt: str,
        messages: List[Dict[str, str]],
        timeout: Optional[float] = None,
        num_predict: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        eff_timeout = timeout or settings.model_timeout_seconds
        url = f"{self._base_url}/api/chat"

        ollama_messages = [{"role": "system", "content": system_prompt}]
        for msg in messages:
            ollama_messages.append({"role": msg["role"], "content": msg["content"]})

        options: Dict[str, Any] = {
            "num_ctx": 8192,
            "temperature": 0.3,
        }
        if num_predict:
            options["num_predict"] = num_predict

        payload = {
            "model": self._model,
            "messages": ollama_messages,
            "stream": True,
            "options": options,
        }

        try:
            async with httpx.AsyncClient(timeout=eff_timeout) as client:
                async with client.stream("POST", url, json=payload) as response:
                    if response.status_code != 200:
                        err_text = await response.aread()
                        logger.error(
                            "provider_unavailable",
                            extra={"provider": "ollama", "status": response.status_code, "body": err_text[:200].decode("utf-8", errors="ignore")},
                        )
                        raise ModelUnavailableError(
                            f"Ollama returned HTTP status {response.status_code}"
                        )

                    async for line in response.aiter_lines():
                        if not line or not line.strip():
                            continue
                        try:
                            chunk = json.loads(line)
                        except json.JSONDecodeError:
                            continue

                        delta = chunk.get("message", {}).get("content", "")
                        if delta:
                            yield delta

                        if chunk.get("done", False):
                            break

        except (httpx.ConnectError, httpx.ConnectTimeout) as e:
            logger.error("provider_unavailable", extra={"provider": "ollama", "reason": "unreachable"})
            raise OllamaUnavailableError(
                f"Host Ollama service is unreachable at {self._base_url}. Ensure Ollama is running."
            ) from e
        except httpx.TimeoutException as e:
            logger.error("provider_timeout", extra={"provider": "ollama", "timeout": eff_timeout})
            raise ModelTimeoutError(
                f"Ollama generation timed out after {eff_timeout} seconds."
            ) from e
        except Exception as e:
            if isinstance(e, (OllamaUnavailableError, ModelTimeoutError, ModelUnavailableError)):
                raise
            logger.error("agent_generation_failed", extra={"provider": "ollama", "error": str(e)})
            raise ModelUnavailableError(f"Ollama generation failed: {str(e)}") from e


class FakeLLMProvider(LLMProvider):
    """Deterministic fake provider for automated tests and offline simulation."""

    def __init__(
        self,
        tokens: Optional[List[str]] = None,
        model: str = "fake-model",
        error_to_raise: Optional[Exception] = None,
        delay_per_token: float = 0.0,
    ):
        self._tokens = tokens if tokens is not None else ["According to ", "Lenny's Podcast, ", "growth loops ", "are essential."]
        self._model = model
        self._error_to_raise = error_to_raise
        self._delay_per_token = delay_per_token
        self.invoked = False
        self.invocations: List[dict] = []

    @property
    def provider_name(self) -> str:
        return "fake"

    @property
    def model_name(self) -> str:
        return self._model

    async def stream_chat(
        self,
        system_prompt: str,
        messages: List[Dict[str, str]],
        timeout: Optional[float] = None,
        num_predict: Optional[int] = None,
    ) -> AsyncGenerator[str, None]:
        self.invoked = True
        self.invocations.append({
            "system_prompt": system_prompt,
            "messages": messages,
            "timeout": timeout,
            "num_predict": num_predict,
        })

        if self._error_to_raise:
            raise self._error_to_raise

        for token in self._tokens:
            if self._delay_per_token > 0:
                await asyncio.sleep(self._delay_per_token)
            yield token


def get_llm_provider(provider_name: Optional[str] = None) -> LLMProvider:
    """Factory function to instantiate the configured or requested reasoning provider."""
    name = (provider_name or settings.active_llm_provider).lower().strip()

    if name in ("anthropic", "claude"):
        return AnthropicProvider()
    elif name == "ollama":
        return OllamaProvider()
    elif name == "fake":
        return FakeLLMProvider()
    else:
        raise ValueError(f"Unsupported LLM provider: '{name}'. Supported providers: 'anthropic', 'ollama'.")
